---
apiVersion: v1
kind: Service
metadata:
  name: job-svc
spec:
  clusterIP: None
  selector:
    job-name: dns-test

---
apiVersion: batch/v1
kind: Job
metadata:
  name: dns-test
spec:
  completions: 3
  parallelism: 3
  completionMode: Indexed
  template:
    metadata:
      labels:
        type: dns
    spec:
      subdomain: job-svc
      containers:
      - name: test
        image: busybox
        imagePullPolicy: IfNotPresent
        command:
        - sh
        - -c
        - |
          for i in 0 1 2
          do
            sleep 2
            status="-1"
            while [ $status -ne 0 ]
            do
              ip=`nslookup dns-test-${i}.job-svc.default.svc.cluster.local | awk -F': ' 'NR==6 { print $2 } '`
              if [ "$ip" == "" ]; then
                echo "Failed to resolve pod's dns name dns-test-${i}.job-svc, retrying in 1 second..."
                sleep 1
              else
                status=0
              fi
            done
            echo "Successfully resolve pod's dns name: dns-test-${i}.job-svc "$ip
          done
      restartPolicy: Never
