apiVersion: batch/v1
kind: Job
metadata:
  name: job-indexed
spec:
  completions: 5
  parallelism: 3
  completionMode: Indexed
  template:
    metadata:
      labels:
        type: indexed
    spec:
      containers:
      - name: pring-index
        image: busybox
        imagePullPolicy: IfNotPresent
        command:
        - "sh"
        - "-c"
        - "echo my index=$JOB_COMPLETION_INDEX"
      restartPolicy: Never
