apiVersion: batch/v1
kind: Job
metadata:
  name: job-podfailurepolicy
spec:
  completions: 9
  parallelism: 3
  backoffLimit: 9
  podFailurePolicy:
    rules:
    - action: FailJob
      onExitCodes:
        containerName: main
        operator: In
        values: [2,4]
  template:
    metadata:
      labels:
        type: exception
    spec:
      containers:
      - name: main
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ["sh", "-c", "sleep 1 && c=`expr $RANDOM % 6` && echo exit $c && exit $c"]
      restartPolicy: Never
