apiVersion: v1
kind: Pod
metadata:
  name: pod-with-init
  labels:
    app: nginx
spec:
  initContainers:
  - name: install
    image: busybox
    imagePullPolicy: IfNotPresent
    command: ["sh", "-c", "echo Hello World! > /web-root/index.html" ]
    volumeMounts:
    - name: webroot
      mountPath: "/web-root"
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
    volumeMounts:
    - name: webroot
      mountPath: /usr/share/nginx/html
  volumes:
  - name: webroot
    emptyDir: {}
