apiVersion: v1
kind: Pod
metadata:
  name: pod-with-init-3
spec:
  initContainers:
  - name: register-to-svc-center
    image: busybox
    imagePullPolicy: IfNotPresent
    command:
    - sh
    - -c
    - until curl -X POST -d 'svc_name=$POD_NAME&svc_ip=$POD_IP' http://$SERVICE_REGISTRY_HOST:$SERVICE_REGISTRY_PORT/register; do echo -e "register to service center"; sleep 5; done; echo -e "register successfully, starting service now";
    env:
    - name: SERVICE_REGISTRY_HOST
      value: 192.168.10.1
    - name: SERVICE_REGISTRY_PORT
      value: 8080
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
  containers:
  - name: service
......
